/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPessoasRouteImport } from './routes/_app.pessoas'
import { Route as AppGerarRouteImport } from './routes/_app.gerar'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCartoesRouteImport } from './routes/_app.cartoes'
import { Route as AppCartaoIdRouteImport } from './routes/_app.cartao.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppGerarRoute = AppGerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCartaoIdRoute = AppCartaoIdRouteImport.update({
  id: '/cartao/$id',
  path: '/cartao/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cartoes': typeof AppCartoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/gerar': typeof AppGerarRoute
  '/pessoas': typeof AppPessoasRoute
  '/cartao/$id': typeof AppCartaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cartoes': typeof AppCartoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/gerar': typeof AppGerarRoute
  '/pessoas': typeof AppPessoasRoute
  '/cartao/$id': typeof AppCartaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cartoes': typeof AppCartoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gerar': typeof AppGerarRoute
  '/_app/pessoas': typeof AppPessoasRoute
  '/_app/cartao/$id': typeof AppCartaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cartoes'
    | '/dashboard'
    | '/gerar'
    | '/pessoas'
    | '/cartao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cartoes'
    | '/dashboard'
    | '/gerar'
    | '/pessoas'
    | '/cartao/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/cartoes'
    | '/_app/dashboard'
    | '/_app/gerar'
    | '/_app/pessoas'
    | '/_app/cartao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gerar': {
      id: '/_app/gerar'
      path: '/gerar'
      fullPath: '/gerar'
      preLoaderRoute: typeof AppGerarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes': {
      id: '/_app/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartao/$id': {
      id: '/_app/cartao/$id'
      path: '/cartao/$id'
      fullPath: '/cartao/$id'
      preLoaderRoute: typeof AppCartaoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCartoesRoute: typeof AppCartoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGerarRoute: typeof AppGerarRoute
  AppPessoasRoute: typeof AppPessoasRoute
  AppCartaoIdRoute: typeof AppCartaoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartoesRoute: AppCartoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGerarRoute: AppGerarRoute,
  AppPessoasRoute: AppPessoasRoute,
  AppCartaoIdRoute: AppCartaoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
